"use strict";

const STATES = Object.freeze(["SCANNING", "TREND_FOUND", "WAIT_PULLBACK", "WAIT_BREAKOUT", "WAIT_RETEST", "WAIT_CONTINUATION", "WAIT_ENTRY_ALIGNMENT", "WAIT_STRUCTURE_SPACE", "READY_A", "READY_B", "BLOCKED", "ENTERED", "MANAGING", "DEFENSIVE", "EXITED", "REENTRY_COOLDOWN"]);
function normalizeSetupState(value) { return STATES.includes(value) ? value : "SCANNING"; }
const ALLOWED = Object.freeze({
  SCANNING: ["TREND_FOUND", "WAIT_PULLBACK", "WAIT_BREAKOUT", "WAIT_RETEST", "WAIT_CONTINUATION", "WAIT_ENTRY_ALIGNMENT", "WAIT_STRUCTURE_SPACE", "READY_A", "READY_B", "BLOCKED"],
  TREND_FOUND: ["SCANNING", "WAIT_PULLBACK", "WAIT_BREAKOUT", "WAIT_RETEST", "WAIT_CONTINUATION", "WAIT_ENTRY_ALIGNMENT", "READY_A", "READY_B", "BLOCKED"],
  WAIT_PULLBACK: ["SCANNING", "TREND_FOUND", "WAIT_PULLBACK", "WAIT_RETEST", "WAIT_ENTRY_ALIGNMENT", "READY_A", "READY_B", "BLOCKED"],
  WAIT_BREAKOUT: ["SCANNING", "TREND_FOUND", "WAIT_BREAKOUT", "WAIT_RETEST", "WAIT_ENTRY_ALIGNMENT", "READY_A", "READY_B", "BLOCKED"],
  WAIT_RETEST: ["SCANNING", "WAIT_RETEST", "WAIT_PULLBACK", "WAIT_ENTRY_ALIGNMENT", "READY_A", "READY_B", "BLOCKED"],
  WAIT_CONTINUATION: ["SCANNING", "TREND_FOUND", "WAIT_CONTINUATION", "WAIT_ENTRY_ALIGNMENT", "READY_A", "READY_B", "BLOCKED"],
  WAIT_ENTRY_ALIGNMENT: ["SCANNING", "TREND_FOUND", "WAIT_PULLBACK", "WAIT_BREAKOUT", "WAIT_RETEST", "WAIT_CONTINUATION", "WAIT_ENTRY_ALIGNMENT", "READY_A", "READY_B", "BLOCKED"],
  WAIT_STRUCTURE_SPACE: ["SCANNING", "WAIT_STRUCTURE_SPACE", "READY_A", "READY_B", "BLOCKED"],
  READY_A: ["ENTERED", "SCANNING", "TREND_FOUND", "WAIT_PULLBACK", "WAIT_BREAKOUT", "WAIT_RETEST", "WAIT_CONTINUATION", "WAIT_ENTRY_ALIGNMENT", "WAIT_STRUCTURE_SPACE", "BLOCKED", "REENTRY_COOLDOWN"], READY_B: ["ENTERED", "SCANNING", "TREND_FOUND", "WAIT_PULLBACK", "WAIT_BREAKOUT", "WAIT_RETEST", "WAIT_CONTINUATION", "WAIT_ENTRY_ALIGNMENT", "WAIT_STRUCTURE_SPACE", "BLOCKED", "REENTRY_COOLDOWN"],
  BLOCKED: ["SCANNING", "TREND_FOUND", "WAIT_PULLBACK", "WAIT_BREAKOUT", "WAIT_RETEST", "WAIT_CONTINUATION", "WAIT_ENTRY_ALIGNMENT", "READY_A", "READY_B", "BLOCKED"],
  ENTERED: ["MANAGING"], MANAGING: ["MANAGING", "DEFENSIVE", "EXITED"], DEFENSIVE: ["DEFENSIVE", "MANAGING", "EXITED"],
  EXITED: ["REENTRY_COOLDOWN", "SCANNING"], REENTRY_COOLDOWN: ["REENTRY_COOLDOWN", "SCANNING", "TREND_FOUND", "WAIT_PULLBACK", "WAIT_CONTINUATION", "READY_A", "READY_B", "BLOCKED"]
});
function transition(currentState, nextState, event = "") {
  const current = normalizeSetupState(currentState), next = normalizeSetupState(nextState);
  const allowed = current === next || (ALLOWED[current] || []).includes(next);
  return { allowed, state: allowed ? next : current, from: current, to: next, event, error: allowed ? "" : `非法状态迁移 ${current} -> ${next}${event ? ` (${event})` : ""}` };
}
module.exports = { STATES, ALLOWED, normalizeSetupState, transition };
